


//set fixed text
var div = document.createElement('div');
div.innerHTML = "Glaciers of the North Cascades Institute";
div.setAttribute('class', 'note leaflet-map-pane', 'style', 'transform: translate3d(-12.3491px, -70.9766px, 0px);');
document.getElementById('map').appendChild(div);



	var map = L.map('map', {
		crs: L.CRS.Simple,
		center: [0, 10],
		zoom: 3
	})


	var bounds = [[-100,-100], [100,100]];
	var options = {zIndex: 300, className: 'glaciers'}
	var image = L.imageOverlay('ncascades-contour-hillshade.svg', bounds, options).addTo(map);


	var options = {interval: 20,
	               showOriginLabel: false,
	               redraw: 'move',
	               zoomIntervals: [
	                {start: 0, end: 3, interval: 40},
	                {start: 4, end: 5, interval: 10},
	                {start: 6, end: 20, interval: 2}
	            ]};

	// // add tile layers to leaflet-tile-pane div class //
	// var options = {zIndex: 100, tileSize: 256}
	// L.TileLayer.Blueprint = L.TileLayer.extend({
	// 	getTileUrl: function(coords) {
	// 		var i = Math.ceil( Math.random() * 200 );
	// 		return "../Day2_Diablo-Lake-Trail/blueprint-tiles/00"+i+".png";
	// 	}, options
	// });
	//
	// L.tileLayer.blueprint = function() {
	// 	return new L.TileLayer.Blueprint();
	// }
	//
  // // map.addLayer( L.tileLayer.blue() );
  // map.addLayer( L.tileLayer.blueprint() );

// var options = {maxZoom: 16, tms: true}
//
// 	L.TileLayer.Qtiles = L.TileLayer.extend({
// 		getTileUrl: function(coords) {
// 			return 'file:////Volumes/IANGP/Field Notes/Day9_new-direction/Qtiles/QtilesXYZ/{z}/{x}/{y}.png';
// 		}, options
// 	});.addTo(map);

var mytile =L.tileLayer('file:////Volumes/IANGP/Field Notes/Day9_new-direction/Qtiles/Qtiles.html/Qtiles/{z}/{x}/{y}.png', {
	maxZoom: 16,
	tms: true,
	attribution: 'Generated by QTiles'
}).addTo(map);

// CONSTRUCTION TILES

	// add tile layers to leaflet-tile-pane div class //
	var options = {zIndex: 100, tileSize: 256}
	L.TileLayer.Construction = L.TileLayer.extend({
		getTileUrl: function(coords) {
			var i = Math.ceil( Math.random() * 150 );
			return "../Map_08/construction-tiles-2/00"+i+".png";
		}, options
	});

	L.tileLayer.construction = function() {
		return new L.TileLayer.Construction();
	}

	// map.addLayer( L.tileLayer.blue() );
	map.addLayer( L.tileLayer.construction() );


	L.simpleGraticule(options).addTo(map);
